# TODO: add count_nucleotides()
"""
Count the number of nucleotides occurence
Argument: DNA string
Return: dictionary of count of nucleotide
"""
def count_nucleotides(s:str) -> dict[str, int]:
    dict = {"A":0, "T":0, "C":0, "G":0 }
    for n in s:
        if n in dict:
            dict[n] += 1
    return dict
    
def main() -> None:
    s = "GTCGCGAGCCAGAGGCCAAAACTACCAACGCCAGAAGAACAAATTTCCTCATCTTGCCCCTCTCGACCCACGGTTATTCGTGAAAAACACGTCGGAATATCAGGAGGTCTGTCCCGCAAGATCGTGGATCGGATGGTCTCATGACTTTGACATCCGTACGATTCATAGGACTAACAATTTCGATTTTAGTTGGTAAACTAGCTACCTTTCGTATTCAAGGCACTAGCCTTAGAAAGTGGCCTATGGCAATTGTCACAGCCTATGTGGGTAAGCCTTTGCTTGACAGGACCGACCGTCACCCCAGCCTGAACGATTGACGATACACCTGGCAGGATGGTTCGTGTAGAACTGCAATGGGAGATAAGGCCCGAGCGGTAGCAACGGGATCGCCGATGACGCTGACTCCTAGGGTTACCGAGTATAGACCTCACAAAGGCTTCCCGCCGCGTGGGGGCAGATCCGACGTCATTCGTGTGAGGCGCGCATAGCTTCGTTAGCGATGAAGGGATTTTGCCCGGCAGGTCGGAGTACATAGTTATCCCTGGCTGGCCATCATCCCTAAGAGTTTGACCGTAAGGCATAAGCACTGTACGGAAAGCGGATATTTGATGAAAGTGATATGTATTCGACCTCCGGAGGTGACCCTTTGTGAAGTAGAAATACAACTCATGTTGGTCCAGGTTACACTAGGGTTCCATACTCCGCGGTCGTATGCTCCTCCTCTACGTCTTGTTTTGGGTCGACGTGCAGCGTGCTCCACAGGGAACTTTGACGACCCCCCACGATGTGAAGCGCACATTTCTTCTAGCTTCCTAT"

    counts = count_nucleotides(s)
    print(counts["A"], counts["C"], counts["G"], counts["T"])


if __name__ == "__main__":
    main()