# TODO: add reverse_complement()
"""
Complement then reverse the DNA sequence
Arg: Str
Return Str  
"""
def complement(s:str) -> str:
    comp = []
    for n in s:
       if n == "A": comp.append("T")
       elif  n == "T": comp.append("A")
       elif  n == "C": comp.append("G")
       elif  n == "G": comp.append("C")
    return comp
def reverse_complement(s):
    list = complement(s)
    revc = []
    l = len(list)
    for n in range(l):
        revc.append(list[l-n-1])
    return "".join(revc)
def main() -> None:
    s = "TCGTGCTTGGATGCAGTCCCGATAGTTGCATGCTCCGATGAGTAGGCAGGGCGGGCGCTCTATGGAATGTCTAGACATTCGTGAAAACGGTCAACTTCGTCTCAACCGAACAAGTGCGGGGTAACTTTTTCAAACGCAAAGTGCAGCTTGTAACAGATTCCGCATAGCGGCCTTACCTCCGATGGTACCTGGGAATGTACGTAGTATTCGCTGTCGCTTCTGTTGGGTTGGCAGAGAAGCCACCCCTAGCACAAGGGAAGCTAAGGAACAGTTTCAGGCAGTAAGCGGGATGCGGAATGCGAAGAGATTTGCCGCCCGATAGGCATGATTTCCATGCCGCCTCTGTTCTTTACGGCGTACCGTGGAGCATACCAATGGGGATGACTACCACGTCTTTGCGACGGATCTCGCCCAATTATGGCGGTACTCAAACGCACGTTGACGTAATAGGACTACTGGTCTTATAGTGGACATTCACCACACTACATAGGAGGCATCTACCGATTGACTCAACGGTACTGCCGGCGACGACTGGCTTTCTGCGTTAGACACCCTTCTTATCCCTAATGGAGTACGCGCGGGGTAGCGAGGCTCGTCTTATCTCCTTGTCACGTATCGCGCGTTGGCAACTGTCCTTCTATCCCGAAAGCGTGTGGAGATCCCCAATTGACTGAAAGGGTACGTTACCGCTAACGTCAGCTATCCAAATAGCGCCTCCGCACATGATCGCAATGGGGACCAACATTTTGGCAGTCAAACGCTGGGGTCTCATCGAAGGCTTGAACTGAAGCTCTGGAGACAATTAGATCCAAGGTATTATCGGGAAGAGGCTAAGGTGATGACT"

    result = reverse_complement(s)
    print(result)


if __name__ == "__main__":
    main()