# TODO: add transcribe()
"""
convert T -> U
Argument: string
Return: String
"""
def transcribe (s:str) -> str:
    rna = []
    for n in s:
        if n == "T":
            rna.append("U")
        else:
            rna.append(n)
    return "".join(rna)
        

def main() -> None:
    dna = "CCCACACGTCCGTCTGCTGTGATAGATTTCTCGTGGAAGAGACCGGCCACTGTATCAGGCCCAATCACGCCTCCATAGTCTGAGGCGATGTCGGACGTAAACTTAACTACCCTCTTTGACTCCTGTAGGATCTCAAAACGTCAGGCGAAGCTCCCGCATGTTGCATTGGCATATTAGCGGTGCCCATCGCCGACAGTGAATGTCGATCCCCCCTAGACAGGAGTCAAAAGCGCATGCGTTTTATTACATATGCCAGAAAGTCCACTCTGCGCGGGGAGTACTCGTCCCTAGAGGGCCCTTCTCGGCGTACGATTAGTAGTGTCTCAACGGTGTCTAAAGAACTAATCTACAGCTGACATGTGGTTGGTTCATCTTCCTTTTTGTGGCGCCTTATAGCCAGGGTGAGTGTTCGTGCTTGACGTGCTCCCTATAGTGAACGGATGTTTACGGGCTTCTTGCACGCCCGAATCGACGGTTGAACGCCTCTTTAGGGGCAGAGCATGAATTTGGGTCGGTTAATCTGTGAAGTGTCCTAAAAAACTACACCACACCCCCGGATTCTTAACGTCAGTGCTTCCCTCACAGCAGTTACACACCTGGACGTCTACTGGATCAGGGTCCAGCTTATCGTTTTCTAAGGGCCTGGGCCCCTTAATTGAAGCTATTGATGGGCTTTGCCGGTTAGTATGAACTATTCCTCAGACGCCTCGAAATGTCAGTTAACAGACTCCAGGATTGGACTCCGCTACGAGGATAGGAGCCCACATATTATGCTTGCGGGGCGTACTTATGTCCACAGTCACCTTTTCGTAGTCCTCTCATACACGGTCAGGGAGTGTAGGTCGGCTTGGCCACTCAGCTTATCGCCCTGCTTCAGGCTGACATTAGCGGTTCGAACCTCAAGTAAAATTGGAACATAATCAGTACTCGCGCCGCCGCAATTCAATCCCGCTTTATT"

    rna = transcribe(dna)
    print(rna)


if __name__ == "__main__":
    main()