# TODO: add find_substring_positions()

""" 
output starting position of substring
Given a string with length n, a substring with length k has n-l+1 substring with staring position from 0 to n-k.
"""
def find_substring_positions(s:str, t:str) -> list[int]:
    n,k = len(s),len(t)
    if n < k:
        raise ValueError("ValueError: substring is longer than reference string")
    p = []
    for i in range (n-k+1):
        if s[i:i+k] == t:
            p.append(i)
    return p

def main() -> None:
    s = "TTCAATGTCGATAAATGTCGACAAATGTCGTATGGAATGTCGAACAAATGTCGCCAATGTCGAATGTCGGGAACACAATGTCGAATGTCGTCGCAATGTCGAAATGTCGAATGTCGCAAATGTCGAATGTCGTTGAGTGCCAAATGTCGGTCAATGTCGGAATGTCGGGCTGATTAGAAATGTCGAAAAATGTCGGAATGTCGTCATCAGAAATGTCGATAATGTCGAATGTCGAATGTCGGGAATGTCGAATGTCGAAGCAATGTCGAATGTCGCTAATGTCGATAATGTCGACGAGTTAATGTCGTATAAATGTCGGGTAATGTCGCAGCAATGTCGAATGTCGGAAATGTCGCGAGAAATGTCGAATGTCGCGTGAGAGTAATGTCGTAATGTCGCGCGCAATGTCGTAATGTCGCAACTAAATGTCGTGCAATGTCGAAAATGTCGAATGTCGAATGTCGTAATGTCGGGGTGAGAATGTCGAATGTCGAATGTCGAATGTCGTCCAGAATGTCGGAACAATGTCGTTAATGTCGGAAGCATGGAAATGAGTCCCAAATGTCGAATGTCGCTCGAATGTCGATCAATGTCGGATAATGTCGGGCAATGTCGTCGTTGAATGTCGAATGTCGATCAAAATGTCGAATGTCGAATGTCGAATCGAATGTCGTAAAATGTCGAGTAACAATGTCGCGGGAAATGTCGAATGGTAATGTCGGAGGAATGTCGTAATGTCGTGTCAGATTATTCAGCAAATGTCGGAGTAAATGTCGAATGTCGGGTTAATGTCGCGAGAATGTCG"
    t = "AATGTCGAA"

    positions = find_substring_positions(s, t)
    for pos in positions:
        print(pos + 1, end=" ")

if __name__ == "__main__":
    main()